### ISSUE TITLE
Android 4.4 5.1 清单文件里配置android:sharedUserId="android.uid.system" 重启进程异常Unable to get provider android.support.v4.content.FileProvider: java.lang.RuntimeException: Package manager has died，需要重启几次才能正常，虽然bug的到修复

### ISSUE THREAD

**Issue by GankLun** [simpleton/tiny_httpclient#101]

**Comment by GankLun** [comment]
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.reflect.UndeclaredThrowableException
        at android.app.ActivityThread.installProvider(ActivityThread.java:5367)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4878)
        at android.app.ActivityThread.access$1500(ActivityThread.java:190)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5676)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777)
     Caused by: java.lang.reflect.UndeclaredThrowableException
        at $Proxy2.resolveContentProvider(Unknown Source)
        at android.app.ApplicationPackageManager.resolveContentProviderAsUser(ApplicationPackageManager.java:689)
        at android.app.ApplicationPackageManager.resolveContentProvider(ApplicationPackageManager.java:682)
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:582)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557)
        at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:375)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5364)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4878) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:190) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5676) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.tencent.tinker.loader.hotplug.handler.PMSInterceptHandler.a(BUGLY:28)
        at com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor$FakeInterfaceHandler.invoke(BUGLY:237)
        at java.lang.reflect.Proxy.invoke(Proxy.java:397)
        at $Proxy2.resolveContentProvider(Unknown Source) 
        at android.app.ApplicationPackageManager.resolveContentProviderAsUser(ApplicationPackageManager.java:689) 
        at android.app.ApplicationPackageManager.resolveContentProvider(ApplicationPackageManager.java:682) 
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:582) 
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557) 
        at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:375) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:5364) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4878) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:190) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5676) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777) 
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:504)
        at android.content.pm.IPackageManager$Stub$Proxy.resolveContentProvider(IPackageManager.java:2793)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.tencent.tinker.loader.hotplug.handler.PMSInterceptHandler.a(BUGLY:28) 
        at com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor$FakeInterfaceHandler.invoke(BUGLY:237) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
        at $Proxy2.resolveContentProvider(Unknown Source) 
        at android.app.ApplicationPackageManager.resolveContentProviderAsUser(ApplicationPackageManager.java:689) 
        at android.app.ApplicationPackageManager.resolveContentProvider(ApplicationPackageManager.java:682) 
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:582) 
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:557) 
        at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:375) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:5364) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4878) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:190) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5676) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777) 
08-16 12:53:54.013 6440-6440/ecarx.upgrade E/AndroidRuntime: Error reporting crash
    java.lang.reflect.UndeclaredThrowableException
        at $Proxy1.handleApplicationCrash(Unknown Source)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
        at com.tencent.tinker.loader.TinkerUncaughtHandler.uncaughtException(BUGLY:51)
        at com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler.uncaughtException(BUGLY:36)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.tencent.tinker.loader.hotplug.handler.AMSInterceptHandler.a(BUGLY:72)
        at com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor$FakeInterfaceHandler.invoke(BUGLY:237)
        at java.lang.reflect.Proxy.invoke(Proxy.java:397)
        at $Proxy1.handleApplicationCrash(Unknown Source) 
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89) 
        at com.tencent.tinker.loader.TinkerUncaughtHandler.uncaughtException(BUGLY:51) 
        at com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler.uncaughtException(BUGLY:36) 
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693) 
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690) 
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:504)
        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4296)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.tencent.tinker.loader.hotplug.handler.AMSInterceptHandler.a(BUGLY:72) 
        at com.tencent.tinker.loader.hotplug.interceptor.ServiceBinderInterceptor$FakeInterfaceHandler.invoke(BUGLY:237) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
        at $Proxy1.handleApplicationCrash(Unknown Source) 
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89) 
        at com.tencent.tinker.loader.TinkerUncaughtHandler.uncaughtException(BUGLY:51) 
        at com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler.uncaughtException(BUGLY:36) 
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693) 
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by simpleton** [comment]
造成问题的原因是tinker有逻辑在加载完毕补丁后去kill其他进程，如果配置了'android:sharedUserId="android.uid.system', 会尝试去kill系统的其他进程，进而导致问题。

**Comment by GankLun** [comment]
目前我自己通过JavaAssist 改了字节码，通过包名判断只杀自身包名相关的进程，你觉得这样处理是否妥当，因为按照现在的代码来看，会把系统进程杀了
