### ISSUE TITLE
tinker加载失败导致应用闪退

### ISSUE THREAD

**Issue by FLx1** [simpleton/tiny_httpclient#148]

**Comment by FLx1** [comment]
08-11 14:56:17.570166  3189  3189 D AndroidRuntime: Shutting down VM
--------- switch to crash
08-11 14:56:17.570745  3189  3189 E AndroidRuntime: JUNK_FATAL_EXCEP: FATAL EXCEPTION: main,Process: com.kaola, PID: 3189
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: FATAL EXCEPTION: main
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: Process: com.kaola, PID: 3189
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.kaola.app.HTApplicationInternal: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5971)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:206)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6773)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:null
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(Unknown Source:49)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1157)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5966)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	... 8 more
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.tencent.tinker.loader.app.TinkerApplication.onCreate(Unknown Source:26)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	... 10 more
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1956)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.android.internal.telephony.ISub$Stub$Proxy.getActiveSubscriptionInfoList(ISub.java:589)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at android.telephony.SubscriptionManager.getActiveSubscriptionInfoList(SubscriptionManager.java:816)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.cmic.sso.sdk.a.b.h(Unknown Source:11)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.cmic.sso.sdk.a.b.f(Unknown Source:16)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.cmic.sso.sdk.a.b.b(Unknown Source:27)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.cmic.sso.sdk.auth.AuthnHelper.getNetworkType(Unknown Source:37)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.netease.urs.android.sfl.SdkHelper.getOperatorType(Unknown Source:22)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.modules.account.newlogin.presenter.CommonLoginPresenter.bP(Unknown Source:0)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.modules.account.a.Eo(Unknown Source:9)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.modules.account.b.onAppStart(Unknown Source:8)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.app.b.e.zJ(Unknown Source:69)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.app.b.e.onCreate(Unknown Source:759)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.app.HTApplication.onCreateAfterPermissionGrated(Unknown Source:11)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	at com.kaola.app.HTApplication.onCreate(Unknown Source:247)
08-11 14:56:17.571118  3189  3189 E AndroidRuntime: 	... 12 more
