### ISSUE TITLE
集成tinkerpatch后运行release版本，android 8.0 华为设备 闪退，求指点

### ISSUE THREAD

**Issue by weituo** [simpleton/tiny_httpclient#152]
--------- beginning of crash
09-16 12:51:07.019 6725-6725/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pop.android:patch, PID: 6725
    java.lang.AbstractMethodError: abstract method "boolean android.app.job.JobServiceEngine.onStartJob(android.app.job.JobParameters)"
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
09-16 12:51:07.019 6725-6725/? W/System.err: java.lang.AbstractMethodError: abstract method "boolean android.app.job.JobServiceEngine.onStartJob(android.app.job.JobParameters)"
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by simpleton** [comment]
可以升级到最新的1.2.14试试
