### ISSUE TITLE
打包后运行在4.4.4手机上crash，同事相同配置的电脑打的包无问题，求分析原因

### ISSUE THREAD

**Issue by xingjiyuan** [simpleton/tiny_httpclient#76]
异常类型：app运行时异常

手机型号：Nexus 5

手机系统版本：Android 4.4.4 

tinker版本：com.tencent.bugly:tinker-support 1.0.8 对应 tinker 1.7.11

gradle版本：com.android.tools.build:gradle:2.2.3
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip

系统：win10

堆栈/日志：
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.jiemian.news, PID: 19265
                                                                  java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
                                                                      at android.app.LoadedApk.makeApplication(LoadedApk.java:507)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                   Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
                                                                      at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:70)
                                                                      at android.app.Application.attach(Application.java:181)
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                      at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                      at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:68)
                                                                      at android.app.Application.attach(Application.java:181) 
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                      at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: java.lang.NoClassDefFoundError: com.jiemian.news.activity.MyApplication$1
                                                                      at com.jiemian.news.activity.MyApplication.<init>(MyApplication.java:60)
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                      at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:68) 
                                                                      at android.app.Application.attach(Application.java:181) 
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                      at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                      at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                      at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:136) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by simpleton** [comment]
bugly的问题可以直接向bugly的客服同学反馈。
